apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "my-ingress"
spec:
  rules:
  - host: "*.example.com"
    http:
      paths:
      - path: "/example"
        pathType: "Prefix"
        backend:
          serviceName: "example-service"
          servicePort: 80
